component_depth: 1
languages:
- java
- script
exclude:
- ./bin/.*
- ./conf/.*
- ./conf/http/.*
- ./conf/http/etc/.*
- ./conf/http/ssi/.*
- ./conf/http/ssi/images/.*
- ./docs/.*
- ./docs/adaptors/.*
- ./docs/adaptors/html/.*
- ./docs/adaptors/rmi/.*
- ./docs/agent/.*
- ./docs/agent/mbeanserver/.*
- ./docs/agent/services/.*
- ./docs/agent/services/mlet/.*
- ./docs/agent/services/monitor/.*
- ./docs/agent/services/monitor/counter/.*
- ./docs/agent/services/monitor/gauge/.*
- ./docs/agent/services/monitor/string/.*
- ./docs/agent/services/timer/.*
- ./docs/apidocs/.*
- ./docs/apidocs/com/.*
- ./docs/apidocs/com/adventnet/.*
- ./docs/apidocs/com/adventnet/adaptors/.*
- ./docs/apidocs/com/adventnet/adaptors/clients/.*
- ./docs/apidocs/com/adventnet/adaptors/clients/rmi/.*
- ./docs/apidocs/com/adventnet/adaptors/html/.*
- ./docs/apidocs/com/adventnet/adaptors/rmi/.*
- ./docs/apidocs/com/adventnet/jmx/.*
- ./docs/apidocs/com/adventnet/jmx/utils/.*
- ./docs/apidocs/javax/.*
- ./docs/apidocs/javax/management/.*
- ./docs/apidocs/javax/management/loading/.*
- ./docs/apidocs/javax/management/modelmbean/.*
- ./docs/apidocs/javax/management/monitor/.*
- ./docs/apidocs/javax/management/relation/.*
- ./docs/apidocs/javax/management/timer/.*
- ./docs/faqs/.*
- ./docs/frames/.*
- ./docs/images/.*
- ./docs/instru/.*
- ./docs/instru/mbeans/.*
- ./docs/instru/mbeans/dynamic/.*
- ./docs/instru/mbeans/model/.*
- ./docs/instru/mbeans/standard/.*
- ./docs/instru/notification/.*
- ./docs/jmx/.*
- ./docs/release_notes/.*
- ./docs/styles/.*
- ./examples/.*
- ./examples/mbeans/.*
- ./examples/mbeans/dynamic/.*
- ./examples/mbeans/model/.*
- ./examples/mbeans/model/xml/.*
- ./examples/mbeans/standard/.*
- ./examples/notification/.*
- ./lib/.*
- ./tutorials/.*
- ./tutorials/classes/.*
- ./tutorials/classes/examples/.*
- ./tutorials/classes/examples/agent/.*
- ./tutorials/classes/examples/applications/.*
- ./tutorials/classes/examples/applications/server/.*
- ./tutorials/classes/examples/mbeans/.*
- ./tutorials/classes/examples/mbeans/dynamic/.*
- ./tutorials/classes/examples/mbeans/standard/.*
- ./tutorials/classes/tutorials/.*
- ./tutorials/classes/tutorials/agent/.*
- ./tutorials/classes/tutorials/application/.*
- ./tutorials/classes/tutorials/application/shoppingcart/.*
- ./tutorials/classes/tutorials/mbeans/.*
- ./tutorials/classes/tutorials/mbeans/dynamic/.*
- ./tutorials/classes/tutorials/mbeans/standard/.*
- ./tutorials/docs/.*
- ./tutorials/docs/agent/.*
- ./tutorials/docs/application/.*
- ./tutorials/docs/jmx/.*
- ./tutorials/docs/mbean/.*
- ./tutorials/docs/styles/.*
- ./tutorials/images/.*
